### PR TITLE
Add libxml-ruby

### PR DESCRIPTION
**Pull request by benoittgt**
This is ruby heap corruption. Don't know if it fit into this list.
Feel free to close the PR if you don't agree.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
It would be great to say somewhere here that the heap corruption was caused by using libxml-ruby and Nokogiri together. If you just use one or the other, they are 👌

**Comment by benoittgt** [comment]
Thankjs @jacobbednarz. I've added the info.

**Comment by jacobbednarz** [comment]
awesome! we are looking to get a release cut for the fix so hopefully it shouldn't be too much longer

**Comment by sergey-alekseev** [comment]
@benoittgt thanks for the contribution! Can you add an upper version boundary for both `libxml-ruby` and `nokogiri`?

**Comment by benoittgt** [comment]
@sergey-alekseev the problem is for the moment no release has been made for `libxml-ruby` probably soon... See https://github.com/xml4r/libxml-ruby/pull/119#issuecomment-222802181

**Pull request merged**
